title: "Lena üíçÔ∏è Heini"
baseURL: "https://reimer.wedding/"

defaultContentLanguage: de
languages:
  de:
    languageCode: de-de
    languageName: Deutsch
  en:
    languageCode: en-de
    languageName: English


params:
  env: production

metaDataFormat: yaml
enableEmoji: true
enableRobotsTXT: true

disableKinds:
  - taxonomies
  - taxonomyTerm

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      table: true
      strikethrough: true
      linkify: true
      taskList: true
      typographer: true
    renderer:
      unsafe: True
  highlight:
    noClasses: false
    style: friendly

sitemap:
  changeFreq: monthly
  priority: 0.5
  filename: sitemap.xml
